networks:
  test-network:
    driver: bridge

services:
  sql-server:
    container_name: dev-sql-server
    user: root
    build:
      context: ./infra/containers/development/db
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: ${DEV_DOCKER_DATABASE_SA_PASSWORD}
      ACCEPT_EULA: Y
    networks:
      - test-network
    ports:
      - "1433:1433"
    volumes:
      - ./infra/containers/development/db/data:/var/opt/mssql/data
  api:
    container_name: dev-golang
    user: root
    build:
      context: ./infra/containers/development
      dockerfile: Dockerfile
    depends_on:
      - sql-server
    environment:
      DB_SQLSERVER_STRING_CONECTION: ${DB_SQLSERVER_STRING_CONECTION}
      JWT_SECRET: ${JWT_SECRET}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      MAILER_SMTP_HOST: ${MAILER_SMTP_HOST}
      MAILER_SMTP_PORT: ${MAILER_SMTP_PORT}
    networks:
      - test-network
    ports:
      - "8080:8080"
    volumes:
      - .:/srv
    command: sh -c 'go mod download && air'
