networks:
  test-network:
    driver: bridge

services:
  api:
    container_name: dev-golang-template
    user: root
    build:
      context: ./infra/containers/development
      dockerfile: Dockerfile
    environment:
      DB_DSN_BETA_AUTOPARTES: ${DB_DSN_BETA_AUTOPARTES}
      # DB_DSN_DOMAIN_2: ${DB_DSN_DOMAIN_2}
      # DB_DSN_DOMAIN_3: ${DB_DSN_DOMAIN_3}
      JWT_SECRET: ${JWT_SECRET}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      MAILER_SMTP_HOST: ${MAILER_SMTP_HOST}
      MAILER_SMTP_PORT: ${MAILER_SMTP_PORT}
    networks:
      - test-network
    ports:
      - "8080:8080"
    volumes:
      - .:/srv
    command: sh -c 'go mod download && air'
