networks:
  test-network:
    driver: bridge

services:
  api:
    container_name: dev-golang
    user: root
    build:
      context: ./infra/containers/development
      dockerfile: Dockerfile
    depends_on:
      - sql-server
    environment:
      DB_DSN_DOMAIN_1: ${DB_DSN_DOMAIN_1}
      DB_DSN_DOMAIN_2: ${DB_DSN_DOMAIN_2}
      DB_DSN_DOMAIN_3: ${DB_DSN_DOMAIN_3}
      JWT_SECRET: ${JWT_SECRET}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      MAILER_SMTP_HOST: ${MAILER_SMTP_HOST}
      MAILER_SMTP_PORT: ${MAILER_SMTP_PORT}
    networks:
      - test-network
    ports:
      - "8080:8080"
    volumes:
      - .:/srv
    command: sh -c 'go mod download && air'
